version: "3.9"
services:
  generate:
    build: .
    entrypoint: [ 'python', 'main.py']
    volumes:
      - output:/output

#  test1:
#    build: .
#    entrypoint: [ 'python', 'test1.py' ]
#    volumes:
#      - output:/output

  all_tests:
    build: .
    entrypoint: [ 'pytest', 'tests' ]


  test_0_a:
    build: .
    entrypoint: [ 'pytest', 'tests/test_0_a.py' ]

volumes:
  output:
