version: "3.9"
services:
  generate:
    build: .
    entrypoint: [ 'python', 'src/main.py', '-config', 'cfg/conf_i.cfg' ]
    volumes:
      - output:/output

  test1:
    build: .
    entrypoint: [ 'python', 'src/test1.py' ]
    volumes:
      - output:/output

volumes:
  output:
